/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quincaillerie.app;

import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTextPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author donfa
 */
public class Accueil_interface extends javax.swing.JFrame {
float total=0;
    /**
     * Creates new form Accueil_interface
     */
    public Accueil_interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jButton1.setText("Nouveau Produit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quincaillerie/app/Rechercher_IMG.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Qte", "Produit", "Prix d'Achat", "Prix de Vente"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Produits", jPanel1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom", "Telephone", "Adresse"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quincaillerie/app/Rechercher_IMG.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jButton2.setText("Nouveau Fournisseur");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap())
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Fournisseurs", jPanel2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom", "Prénom", "Telephone", "Montant"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quincaillerie/app/Rechercher_IMG.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jButton3.setText("Nouveau Client");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton7.setText("Supprimer Client");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jButton3)
                .addGap(74, 74, 74)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap())
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton7)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Clients", jPanel3);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Entrant/Sortant", "Date", "Numéro", "Montant"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable4);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quincaillerie/app/Rechercher_IMG.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jButton4.setText("Nouveau Cheque");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton9.setText("Supprimer Cheque");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jButton4)
                .addGap(73, 73, 73)
                .addComponent(jButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap())
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton4)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton9)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cheques", jPanel4);

        jLabel5.setText("Nom de client : ");

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quincaillerie/app/Rechercher_IMG.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produit", "Prix"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable5MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTable5);

        jButton5.setText("Annuler");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Imprimer");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel6.setText("Qte :");

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jLabel7.setText("Nom de Produit :");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane6.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(27, 27, 27))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton6)))
                        .addGap(26, 26, 26))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(38, 38, 38)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Facture", jPanel5);

        jButton8.setText("Ajouter une commande");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom de Produit", "Qte"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(jTable7);

        jButton10.setText("Supprimer Commande");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("Actualiser");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jButton10)
                .addGap(91, 91, 91)
                .addComponent(jButton11)
                .addGap(98, 98, 98)
                .addComponent(jButton8)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton10)
                    .addComponent(jButton11))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("A Commander", jPanel7);

        jMenu1.setText("Fichier");

        jMenuItem1.setText("Déconnecter");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Quitter");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jTextArea1.setText(jTextArea1.getText()+"********************************\n");
        jTextArea1.setText(jTextArea1.getText()+"Total: "+total);
        try{
            JTextPane textPane = new JTextPane();

        textPane.setText(jTextArea1.getText());

        textPane.print();
        }catch(PrinterException e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            int qte=0;
        String produit="";
        float prixAchat=0;
        float prixVente=0;
        String url = "jdbc:mysql://localhost:3306/quincaillerie";
        String user = "root";
        String pass = "";
        if (jTextField1.getText().equals("")){
            model.setRowCount(0);//faregh el tableau
            
        
            try{
                Connection conn= DriverManager.getConnection(url,user,pass);
                Statement statement=conn.createStatement();
                ResultSet rs = statement.executeQuery("select * from produits ;");
                while (rs.next()){
                    qte=rs.getInt("Qte");
                    produit=rs.getString("Produit");
                    prixAchat=rs.getFloat("Prix_Achat");
                    prixVente=rs.getFloat("Prix_Vente");
                    model.addRow(new Object[]{qte,produit,prixAchat,prixVente});
                }

                statement.close();
                conn.close();
            }catch (SQLException e1){
                System.out.println("Error: "+ e1.getMessage());
            }
        }else {
            model.setRowCount(0);
            try{
                Connection conn= DriverManager.getConnection(url,user,pass);
                Statement statement=conn.createStatement();
                ResultSet rs = statement.executeQuery("select * from produits WHERE Produit LIKE '%"+jTextField1.getText()+"%';");
                while (rs.next()){
                    qte=rs.getInt("Qte");
                    produit=rs.getString("Produit");
                    prixAchat=rs.getFloat("Prix_Achat");
                    prixVente=rs.getFloat("Prix_Vente");
                    model.addRow(new Object[]{qte,produit,prixAchat,prixVente});
                }

                statement.close();
                conn.close();
            }catch (SQLException e1){
                System.out.println("Error: "+ e1.getMessage());
            }
        }
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Nouveau_produit_interface nv_P = new Nouveau_produit_interface();
        nv_P.show();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.setVisible(false);
        login_interface logout = new login_interface();
        logout.show() ;
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         Nouveau_Fournisseur_interface nv_F = new Nouveau_Fournisseur_interface();
        nv_F.show();        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
          DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            String nom="";
        int telephone=0;
        String adresse="";
        
        String url = "jdbc:mysql://localhost:3306/quincaillerie";
        String user = "root";
        String pass = "";
        if (jTextField2.getText().equals("")){
            model.setRowCount(0);//faregh el tableau
            
        
            try{
                Connection conn= DriverManager.getConnection(url,user,pass);
                Statement statement=conn.createStatement();
                ResultSet rs = statement.executeQuery("select * from fournisseurs ;");
                while (rs.next()){
                    nom=rs.getString("Nom");
                    telephone=rs.getInt("Telephone");
                    adresse=rs.getString("Adresse");
                    
                    model.addRow(new Object[]{nom,telephone,adresse});
                }

                statement.close();
                conn.close();
            }catch (SQLException e1){
                System.out.println("Error: "+ e1.getMessage());
            }
        }else {
            model.setRowCount(0);
            try{
                Connection conn= DriverManager.getConnection(url,user,pass);
                Statement statement=conn.createStatement();
                ResultSet rs = statement.executeQuery("select * from fournisseurs WHERE nom LIKE '%"+jTextField2.getText()+"%';");
                while (rs.next()){
                     nom=rs.getString("Nom");
                    telephone=rs.getInt("Telephone");
                    adresse=rs.getString("Adresse");
                    
                    model.addRow(new Object[]{nom,telephone,adresse});

                }

                statement.close();
                conn.close();
            }catch (SQLException e1){
                System.out.println("Error: "+ e1.getMessage());
            }
        }
        
                                
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
          Nouveau_client_interface nv_C = new Nouveau_client_interface();
           nv_C.show(); 
    }//GEN-LAST:event_jButton3MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
            DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
            String nom="";
            String prenom="";
            int telephone=0;
            int montant=0;
        
        String url = "jdbc:mysql://localhost:3306/quincaillerie";
        String user = "root";
        String pass = "";
        if (jTextField3.getText().equals("")){
            model.setRowCount(0);//faregh el tableau
            
        
            try{
                Connection conn= DriverManager.getConnection(url,user,pass);
                Statement statement=conn.createStatement();
                ResultSet rs = statement.executeQuery("select * from clients ;");
                while (rs.next()){
                    nom=rs.getString("Nom");
                    prenom=rs.getString("Prénom") ;
                    telephone=rs.getInt("Telephone");
                    montant=rs.getInt("Montant");
                    
                    model.addRow(new Object[]{nom,telephone,telephone,montant});
                }

                statement.close();
                conn.close();
            }catch (SQLException e1){
                System.out.println("Error: "+ e1.getMessage());
            }
        }else {
            model.setRowCount(0);
            try{
                Connection conn= DriverManager.getConnection(url,user,pass);
                Statement statement=conn.createStatement();
                ResultSet rs = statement.executeQuery("select * from clients WHERE nom LIKE '%"+jTextField3.getText()+"%';");
                while (rs.next()){
                      nom=rs.getString("Nom");
                    prenom=rs.getString("Prénom") ;
                    telephone=rs.getInt("Telephone");
                    montant=rs.getInt("Montant");
                    
                    model.addRow(new Object[]{nom,telephone,telephone,montant});

                }

                statement.close();
                conn.close();
            }catch (SQLException e1){
                System.out.println("Error: "+ e1.getMessage());
            }
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        int index = jTable3.getSelectedRow(); 
        
        String Nom =jTable3.getModel().getValueAt(index, 0).toString();
        
        
        if (Nom.equals("")){
            JOptionPane.showMessageDialog(null, "Veillez selectionner un nom ");
        } else {
        String url = "jdbc:mysql://localhost:3306/quincaillerie";
        String user = "root";
        String pass = "";
            try {
        Connection connection= DriverManager.getConnection(url,user,pass);
        
        Statement statment = connection.createStatement();
        statment.execute(" Delete FROM clients where Nom='"+Nom+"' ") ;
        JOptionPane.showMessageDialog(null, Nom+" est supprimé");
        
        Statement s = connection.createStatement();
        ResultSet rs=s.executeQuery("select * from clients");
        jTable3.setModel(DbUtils.resultSetToTableModel(rs));
        
        
        
        }
        catch(SQLException e1){
                System.out.println("Erreur : "+ e1.getMessage()) ;
            }
        }
    
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        Nouveau_cheque_interface nv_Ch = new Nouveau_cheque_interface();
           nv_Ch.show();
    }//GEN-LAST:event_jButton4MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
                  
            DefaultTableModel model = (DefaultTableModel) jTable4.getModel();
        String ES="";
        String date="";
        long num =0;
        long montant=0;
        String url = "jdbc:mysql://localhost:3306/quincaillerie";
        String user = "root";
        String pass = "";
        if (jTextField4.getText().equals("")){
            model.setRowCount(0);//faregh el tableau
            
        
            try{
                Connection conn= DriverManager.getConnection(url,user,pass);
                Statement statement=conn.createStatement();
                ResultSet rs = statement.executeQuery("select * from cheques ;");
                while (rs.next()){
                    ES=rs.getString("Type");
                    date=rs.getString("Date");
                    num=rs.getLong("Numero");
                    montant=rs.getLong("Montant");
                    model.addRow(new Object[]{ES,date,num,montant});
                }

                statement.close();
                conn.close();
            }catch (SQLException e1){
                System.out.println("Error: "+ e1.getMessage());
            }
        }else {
            model.setRowCount(0);
            try{
                Connection conn= DriverManager.getConnection(url,user,pass);
                Statement statement=conn.createStatement();
                ResultSet rs = statement.executeQuery("select * from cheques WHERE Type LIKE '%"+jTextField4.getText()+"%';");
                while (rs.next()){
                     ES=rs.getString("Type");
                    date=rs.getString("Date");
                    num=rs.getLong("Numero");
                    montant=rs.getLong("Montant");
                    model.addRow(new Object[]{ES,date,num,montant});
                }

                statement.close();
                conn.close();
            }catch (SQLException e1){
                System.out.println("Error: "+ e1.getMessage());
            }
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        commande_interface nv_cm = new commande_interface();
        nv_cm.show();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
              int index = jTable4.getSelectedRow(); 
        
        String Nom =jTable4.getModel().getValueAt(index, 2).toString();
        
        
        if (Nom.equals("")){
            JOptionPane.showMessageDialog(null, "Veillez selectionner le cheque ");
        } else {
        String url = "jdbc:mysql://localhost:3306/quincaillerie";
        String user = "root";
        String pass = "";
            try {
        Connection connection= DriverManager.getConnection(url,user,pass);
        
        Statement statment = connection.createStatement();
        statment.execute(" Delete FROM cheques where Numero='"+Nom+"' ") ;
        JOptionPane.showMessageDialog(null, " le cheque est supprimé");
        
        Statement s = connection.createStatement();
        ResultSet rs=s.executeQuery("select * from cheques");
        jTable4.setModel(DbUtils.resultSetToTableModel(rs));
        
        
        
        }
        catch(SQLException e1){
                System.out.println("Erreur : "+ e1.getMessage()) ;
            }
        }
    
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
          int index = jTable7.getSelectedRow(); 
        
        String Nom =jTable7.getModel().getValueAt(index, 0).toString();
        
        
        if (Nom.equals("")){
            JOptionPane.showMessageDialog(null, "Veillez selectionner un nom ");
        } else {
        String url = "jdbc:mysql://localhost:3306/quincaillerie";
        String user = "root";
        String pass = "";
            try {
        Connection connection= DriverManager.getConnection(url,user,pass);
        
        Statement statment = connection.createStatement();
        statment.execute(" Delete FROM commander where Nom_de_produit='"+Nom+"' ") ;
        JOptionPane.showMessageDialog(null, Nom+" est supprimé");
        
        Statement s = connection.createStatement();
        ResultSet rs=s.executeQuery("select * from commander");
        jTable7.setModel(DbUtils.resultSetToTableModel(rs));
        
        
        
        }
        catch(SQLException e1){
                System.out.println("Erreur : "+ e1.getMessage()) ;
            }
        }
    
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
DefaultTableModel model = (DefaultTableModel) jTable7.getModel();         
        String nom ="" ;
        int qte ;
        
        String url = "jdbc:mysql://localhost:3306/quincaillerie";
        String user = "root";
        String pass = "";
        model.setRowCount(0);//faregh el tableau
            
        
            try{
                Connection conn= DriverManager.getConnection(url,user,pass);
                Statement statement=conn.createStatement();
                ResultSet rs = statement.executeQuery("select * from commander ;");
                while (rs.next()){
                    nom=rs.getString("Nom_de_produit");
                    qte=rs.getInt("Qte");
                    
                    
                    model.addRow(new Object[]{nom,qte});
                }

                statement.close();
                conn.close();
            }catch (SQLException e1){
                System.out.println("Error: "+ e1.getMessage());
            }        
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        
            DefaultTableModel model = (DefaultTableModel) jTable5.getModel();
         
        String produit="";
        
        float prix=0;
        String url = "jdbc:mysql://localhost:3306/quincaillerie";
        String user = "root";
        String pass = "";
        if (jTextField6.getText().equals("")){
            model.setRowCount(0);//faregh el tableau
            
        
            try{
                Connection conn= DriverManager.getConnection(url,user,pass);
                Statement statement=conn.createStatement();
                ResultSet rs = statement.executeQuery("select * from produits ;");
                while (rs.next()){
                    
                    produit=rs.getString("Produit");
                    
                    prix=rs.getFloat("Prix_Vente");
                    model.addRow(new Object[]{produit,prix});
                }

                statement.close();
                conn.close();
            }catch (SQLException e1){
                System.out.println("Error: "+ e1.getMessage());
            }
        }else {
            model.setRowCount(0);
            try{
                Connection conn= DriverManager.getConnection(url,user,pass);
                Statement statement=conn.createStatement();
                ResultSet rs = statement.executeQuery("select * from produits WHERE Produit LIKE '%"+jTextField6.getText()+"%';");
                while (rs.next()){
                    
                    produit=rs.getString("Produit");
                    
                    prix=rs.getFloat("Prix_Vente");
                    model.addRow(new Object[]{produit,prix});
                }

                statement.close();
                conn.close();
            }catch (SQLException e1){
                System.out.println("Error: "+ e1.getMessage());
            }
        }
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jTextArea1.setText("");
        total=0;
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable5MouseClicked
        if(jTextArea1.getText().equals("")){
            if(jTextField5.getText().equals("")){
                JOptionPane.showMessageDialog(null, "vous devez entrer le nom de client!!");
            }else{
                if(jTextField8.getText().equals("")){
                    JOptionPane.showMessageDialog(null, "vous devez entrer la qte!!");
                }else{
                    jTextArea1.setText(jTextArea1.getText()+"Client: "+ jTextField5.getText()+"\n");
                    total=total+Float.parseFloat(jTable5.getModel().getValueAt(jTable5.getSelectedRow(), 1).toString())*Float.parseFloat(jTextField8.getText());
                    System.out.print(total);
                    jTextArea1.setText(jTextArea1.getText()+jTable5.getModel().getValueAt(jTable5.getSelectedRow(), 0).toString()+
                            "   "+jTable5.getModel().getValueAt(jTable5.getSelectedRow(), 1).toString()+
                            "   "+jTextField8.getText()+"   "+
                            Float.parseFloat(jTable5.getModel().getValueAt(jTable5.getSelectedRow(), 1).toString())*Float.parseFloat(jTextField8.getText())+
                            "\n");
                }
            }
        }else{
            if(jTextField8.getText().equals("")){
                    JOptionPane.showMessageDialog(null, "vous devez entrer la qte!!");
                }else{
                    
                    total=total+Float.parseFloat(jTable5.getModel().getValueAt(jTable5.getSelectedRow(), 1).toString())*Float.parseFloat(jTextField8.getText());
                    System.out.print(total);
                    jTextArea1.setText(jTextArea1.getText()+jTable5.getModel().getValueAt(jTable5.getSelectedRow(), 0).toString()+
                            "   "+jTable5.getModel().getValueAt(jTable5.getSelectedRow(), 1).toString()+
                            "   "+jTextField8.getText()+"   "+
                            Float.parseFloat(jTable5.getModel().getValueAt(jTable5.getSelectedRow(), 1).toString())*Float.parseFloat(jTextField8.getText())+
                            "\n");
                }
        }
    }//GEN-LAST:event_jTable5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accueil_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accueil_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accueil_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accueil_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accueil_interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable7;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
